development:
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  pool: 16
  timout: 5000
